### ISSUE TITLE
Error running updateDatabase on Ubuntu

### ISSUE THREAD

**Issue by degenone** [FritzAndFriends/TagzApp#216]
After fiddling with dotnet versions, I managed to get the projects to build and to make the commands "work" but unfortunately there are still issues.

Just to be sure, I removed both my docker container and image and reran `./launchdb`

Running `./updateDatabase` results in an error.
<details>
  <summary>Show error.</summary>

```bash
$ ./updateDatabase 
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (
          SELECT 1 FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname='public' AND
                c.relname='__EFMigrationsHistory'
      )
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (
          SELECT 1 FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname='public' AND
                c.relname='__EFMigrationsHistory'
      )
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "MigrationId", "ProductVersion"
      FROM "__EFMigrationsHistory"
      ORDER BY "MigrationId";
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (
          SELECT 1 FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname='public' AND
                c.relname='__EFMigrationsHistory'
      )
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT EXISTS (
          SELECT 1 FROM pg_catalog.pg_class c
          JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname='public' AND
                c.relname='__EFMigrationsHistory'
      )
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "MigrationId", "ProductVersion"
      FROM "__EFMigrationsHistory"
      ORDER BY "MigrationId";
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20230826182104_First Commit'.
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20230826182104_First Commit'.
Applying migration '20230826182104_First Commit'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "Content" (
          "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
          "Provider" character varying(20) NOT NULL,
          "ProviderId" character varying(50) NOT NULL,
          "HashtagSought" text NOT NULL,
          "Type" integer NOT NULL,
          "SourceUri" character varying(1000) NOT NULL,
          "Timestamp" timestamp with time zone NOT NULL,
          "Author" text NOT NULL,
          "Text" text NOT NULL,
          "PreviewCard" text,
          "Emotes" text,
          CONSTRAINT "PK_Content" PRIMARY KEY ("Id"),
          CONSTRAINT "AK_Content_Provider_ProviderId" UNIQUE ("Provider", "ProviderId")
      );
Failed executing DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Content" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Provider" character varying(20) NOT NULL,
    "ProviderId" character varying(50) NOT NULL,
    "HashtagSought" text NOT NULL,
    "Type" integer NOT NULL,
    "SourceUri" character varying(1000) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Author" text NOT NULL,
    "Text" text NOT NULL,
    "PreviewCard" text,
    "Emotes" text,
    CONSTRAINT "PK_Content" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Content_Provider_ProviderId" UNIQUE ("Provider", "ProviderId")
);
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "Content" (
          "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
          "Provider" character varying(20) NOT NULL,
          "ProviderId" character varying(50) NOT NULL,
          "HashtagSought" text NOT NULL,
          "Type" integer NOT NULL,
          "SourceUri" character varying(1000) NOT NULL,
          "Timestamp" timestamp with time zone NOT NULL,
          "Author" text NOT NULL,
          "Text" text NOT NULL,
          "PreviewCard" text,
          "Emotes" text,
          CONSTRAINT "PK_Content" PRIMARY KEY ("Id"),
          CONSTRAINT "AK_Content_Provider_ProviderId" UNIQUE ("Provider", "ProviderId")
      );
Npgsql.PostgresException (0x80004005): 42P07: relation "Content" already exists
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "Content" already exists
    File: heap.c
    Line: 1146
    Routine: heap_create_with_catalog
42P07: relation "Content" already exists
```
</details>

<details>
  <summary>Some details about my machine.</summary>
  
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
```bash
$ uname -a
Linux home-ubuntu 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
 ```
```bash
$ dotnet --list-sdks
7.0.111 [/home/<user>/.dotnet/sdk]
8.0.100-preview.6.23330.14 [/home/<user>/.dotnet/sdk]
8.0.100-rc.1.23455.8 [/home/<user>/.dotnet/sdk]
```
```bash
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.11 [/home/<user>/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [/home/<user>/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/home/<user>/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.11 [/home/<user>/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [/home/<user>/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/home/<user>/.dotnet/shared/Microsoft.NETCore.App]
```
```bash
$ dotnet ef --version
Entity Framework Core .NET Command-line Tools
8.0.0-rc.1.23419.6
``` 
```bash
$ docker --version
Docker version 24.0.6, build ed223bc
``` 
</details>

Something is going wrong with `Content` table, it exists when `Applying migration '20230826182104_First Commit'.`

**Comment by degenone** [comment]
On my windows machine, I tried creating a new container (I just changed the name to `pgTagz2` → `docker run -d --name pgTagz2 -e POSTGRES_USER=tagz -e POSTGRES_PASSWORD=tagz -p 5432:5432 postgres`) and it failed in the same way, so this does not seem to be OS depended. **Unless I'm the only one that has this issue?**

I also tried to drop tables when `ef` complained that they already exist and eventually got to the point when it says `No migrations were applied. The database is already up to date.` But when I run the app I get an error:
```bash
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "AspNetRoles" does not exist
    Position: 73
    File: parse_relation.c
    Line: 1392
    Routine: parserOpenTable

dotnet watch ❌ Exited with error code -532462766
```

**Comment by csharpfritz** [comment]
There's two sets of migrations to be applied... since it was decided to keep the content provider model as well as the security model.

This **REALLY** needs some docs and a script to make it easier to configure database for the app

**Comment by csharpfritz** [comment]
I think I have this ironed out with the changes that we applied during stream on Oct 3 to my youtube provider feature branch.  I'll have that merged and available later today

**Comment by csharpfritz** [comment]
This feature has been merged into the main branch.  Please try again and let me know your findings

**Comment by degenone** [comment]
I tried updating a fresh Postgres container and it ran successfully. I caught a glimpse of red when it was running and it was: 
```bash
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" character varying(150) NOT NULL,
          "ProductVersion" character varying(32) NOT NULL,
          CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
      );
``` 
But the app does seem to run properly after.

**Comment by csharpfritz** [comment]
I'll close this for now.  If it crops up again, we'll open another ticket
