### ISSUE TITLE
Error in TwitchChat Provider

### ISSUE THREAD

**Issue by degenone** [FritzAndFriends/TagzApp#228]
Before adding my Twitch credentials I got this error:

```bash
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.Collections.Generic.KeyNotFoundException: The given key 'ClientId' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at TagzApp.Providers.TwitchChat.StartTwitchChat.MapConfigurationValues(ProviderConfiguration providerConfiguration) in C:\Users\Tero\git\TagzApp\src\TagzApp.Providers.TwitchChat\StartTwitchChat.cs:line 39
    ...
```

I think the null check in [StartTwitchChat.MapConfigurationValues](https://github.com/FritzAndFriends/TagzApp/blob/main/src/TagzApp.Providers.TwitchChat/StartTwitchChat.cs#L37) is never null and causes the `KeyNotFoundException`.

This can be fixed by changing `MapConfigurationValues` to have:

```c#
_TwitchChatConfiguration = new TwitchChatConfiguration
{
    ClientId = config.TryGetValue("ClientId", out string? id) ? id : string.Empty,
    ClientSecret = config.TryGetValue("ClientSecret", out string? secret) ? secret : string.Empty,
    ChatBotName = config.TryGetValue("ChatBotName", out string? botName) ? botName : string.Empty,
    OAuthToken = config.TryGetValue("OAuthToken", out string? token) ? token : string.Empty,
    ChannelName = config.TryGetValue("ChannelName", out string? channelName) ? channelName : string.Empty
};
``` 

**Instead of this change, shoud we have it fail more gracefully in a `try {} catch {}`?** Then let the user know those values are missing.

**Comment by csharpfritz** [comment]
Ooh..  good catch.  I'll put together a fix.

This feels like something that should surface in the configuration provider UI as well
